### ISSUE TITLE
Inference Code Issue

### ISSUE THREAD

**Issue by Jianqiuer** [zhiyuanYU134/MIRETR#5]
Dear Zhiyuan

Thank you for sharing your valuable work with the community. I have been working on the provided code for the ROBI dataset in this repository. However, I have encountered some issues and confusion with the provided code. Could we have an email address for further discussion on this matter?

Thank you very much for your time and assistance.

Here is my email: jianqiu@stu.hit.edu.cn

Best regards

**Comment by zhiyuanYU134** [comment]
My email is yuzhiyuan317@gmail.com.

**Comment by Jianqiuer** [comment]
Thank you for your response.

I would like to clarify that the official ROBI dataset provides two versions of the 3D object models. In my implementation, I have opted to load the CAD model version rather than the [reconstructed model](https://drive.google.com/file/d/1mdY9qmlWwYYY4rX7YBWaE1X1tBJDBq7o/view?usp=sharing). While this choice allows the program to run successfully, it results in a discrepancy in accuracy.
